version: '3'
services:
  postgres-server:
    image: postgres:9.6-alpine3.15
    environment:
      POSTGRES_PASSWORD: "Pa55w0rd1234"
    ports:
      - "5416:5432"
  user-api:
    depends_on:
      - postgres-server
    build: .
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: 8001
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_Kestrel__Certificates__Development__Password: "pa55w0rd1234"
    ports:
      - "8000:80"
      - "8001:443"
